version: '3.7'

services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_USER=docker
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=sushi-chat
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  mariadb_data:
